---
include:
  - board: seeeduino_xiao_ble
    shield: grin3_dm rgbled_adapter
    snippet: studio-rpc-usb-uart zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: Test_R
    snippet: zmk-usb-logging