---
include:
  - board: seeeduino_xiao_ble
    shield: grin3
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: geacon rgbled_adapter
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset